const f = () =>{
try{
    let a = 0;
    console.log(progaram);
    console.log("Program run successfully");
}catch(err){
    console.log("This is error")
}
finally{
    console.log("I am a good boy");
}}
f();